name: nsdf-cookbook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pip
  - matplotlib
  - bokeh
  - xmltodict
  - colorcet
  - boto3
  - basemap
  - pip:
      - OpenVisus
      - openvisuspy
